name: Actualizar GeoJSON

on:
  schedule:
    - cron: '*/5 * * * *'  # cada 10 minutos UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_KEY_PURPLEAIR: ${{ secrets.API_KEY_PURPLEAIR }}
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script
        run: python script.py

      - name: Subir archivo actualizado
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add sensores.geojson historico.csv AQ_PM25.geojson AQ_PM10.geojson
          git commit -m "Auto: actualización de archivos GeoJson" || echo "Sin cambios"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
